name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        fast-fail: false
        os:
          - ubuntu-latest
          - macos-latest
        emacs-version:
          - 26.1
          - 26.2
          - 26.3
          - 27.1
          - 27.2
          - 28.1
          - snapshot

    steps:
      - uses: actions/checkout@v2
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: emacs-eask/setup-eask@master
        with:
          version: 'snapshot'
      - uses: actions/cache@v2
        id: cache-eask-packages-000
        with:
          path: .eask
          key: cache-eask-packages
      - name: "Run tests"
        run: make all
